### ISSUE TITLE
Email validation from hell...

### ISSUE THREAD

**Issue by assertchris** [tightenco/symposium#42] opened 2015-03-17 02:28 UTC
![screen shot 2015-03-17 at 3 27 40 pm](https://cloud.githubusercontent.com/assets/200609/6680302/321623cc-ccba-11e4-8e19-e24054a05a16.png)

...using the email "cgpitt@gmail.com"

**Comment by mattstauffer** [comment] 2015-04-06 15:18
@assertchris WTF, yet another thing I didn't get notified about. Sorry! Will check

**Comment by mattstauffer** [comment] 2015-05-07 16:37
@assertchris Can't reproduce this. Is it still happening?

**Comment by mattstauffer** [comment] 2016-06-05 12:52
Closing because can't reproduce.

**Closed by mattstauffer** 2016-06-05 12:52 UTC
Labels: bug
