### ISSUE TITLE
"Unsubmit" talk seems to delete the conference

### ISSUE THREAD

**Issue by greydnls** [tightenco/symposium#104] opened 2015-08-24 16:01 UTC
Working locally, I created a conference, created a talk. I marked that talk as "submitted" to my test conference. 

Once I clicked "unsubmit", the conference gets deleted as well.

**Comment by mattstauffer** [comment] 2015-08-27 19:59
Tried to reproduce; added a test here: 
https://github.com/tightenco/symposium/pull/105/files#diff-7d2dcd5e3ea1984abc236f9c03692367R46
(not merged yet, but is green when I run it right now.)

Can you reproduce it?

**Comment by mattstauffer** [comment] 2016-06-05 13:26
Closing because can't reproduce.

**Closed by mattstauffer** 2016-06-05 13:26 UTC
